import type { Metadata } from "next";
import { Source_Sans_3, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const fontSans = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Warkop Fatahillah",
  description: "Generated by Ardiansyah & Farhan Maulana",
  // Untuk Thema Dark
  // icons: {
  //   icon: {
  //     url: "/favicon-light.ico",
  //     media: "(prefers-color-scheme: light)",
  //   },
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-none">
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased scrollbar-none`}
      >
        {children}
      </body>
    </html>
  );
}
