import type { Metadata } from "next";
import { Source_Sans_3, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const fontSans = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Warkop Fatahillah",
  description: "Generated by Ardiansyah & Farhan Maulana",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        {/* <nav className="fixed top-0 left-0 w-full bg-white/10 backdrop-blur-md p-4 flex justify-between items-center">
        <div className="bg-black rounded-lg">
          <h1 className="text-white text-2xl font-bold m-4">Logo Warkop</h1>

        </div>
      </nav> */}

        {children}
      </body>
    </html>
  );
}
